# -*- coding: utf-8 -*-
"""Final Notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ALNdYClirOM68Y3QuCshOEO9L03wlVV
"""

!nvidia-smi



pip install ultralytics

import ultralytics
ultralytics.checks()

from ultralytics import YOLO
from PIL import Image

from google.colab import drive
drive.mount('/content/drive')

"""# Public dataset

## Model 1: version 37 -> Yolov8n: with integrated augmentations
"""

# Load YOLOv8n model from pre trained
#Loading the previous(result 2) best iteration for training
model_path = "/content/drive/MyDrive/Colab Notebooks(NEHA)/Results/Result2/detect/train/weights/best.pt"
model = YOLO(model_path)

# Freeze
freeze = [f"model.{x}." for x in range(22)]  # layers to freeze
for k, v in model.named_parameters():
    v.requires_grad = True  # train all layers
    if any(x in k for x in freeze):
        print(f"freezing {k}")
        v.requires_grad = False

# Train the model
model.train(data="/content/drive/MyDrive/Colab Notebooks(NEHA)/Datasets/Pothole.v1-raw.yolov8/Pothole.v1-raw.yolov8/data.yaml", epochs=300, optimizer= 'AdamW', batch=64,lr0=0.01, momentum=0.937, patience=50,hsv_h=0.015,hsv_s=0.7,degrees=0.0,scale=0.5,shear=0.5,perspective=0.0,flipud=0.2,fliplr=0.5,mosaic=1.0,translate=0.1)

metrics = model.val()

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard

tensorboard --logdir runs

"""## Running inference (Version 37) (test set)"""

import time

# Load the model
model_path = "/content/drive/MyDrive/Colab Notebooks(NEHA)/Results/Result37/detect/train/weights/best.pt"
model = YOLO(model_path)

# Define path to directory containing images and videos for inference
source = '/content/drive/MyDrive/Colab Notebooks(NEHA)/Datasets/Pothole.v1-raw.yolov8/Pothole.v1-raw.yolov8/test/images'

# Start time recording
start_time = time.time()

# Run inference on the source
results = model.predict(source, save=True, show=True, show_labels=True, show_boxes=True, show_conf=True)

# End time recording
end_time = time.time()

# Calculate and print the elapsed time
elapsed_time = end_time - start_time
print(f"Time taken for inference: {elapsed_time:.2f} seconds")

"""Running validation on it to get the scores"""

import time
# Load the model
model_path = "/content/drive/MyDrive/Colab Notebooks(NEHA)/Results/Result37/detect/train/weights/best.pt"
model = YOLO(model_path)

# Define path to directory containing images and videos for inference
#data = '/content/drive/MyDrive/Colab Notebooks(NEHA)/Datasets/Pothole data augmentation2.v4i.yolov8/test/images'

# Start time recording
start_time = time.time()

#changing the path in data.yaml for test set
metrics = model.val(data ="/content/drive/MyDrive/Colab Notebooks(NEHA)/Datasets/Pothole.v1-raw.yolov8/Pothole.v1-raw.yolov8/data_test.yaml", iou=0.6, save=True)

# End time recording
end_time = time.time()

# Calculate and print the elapsed time
elapsed_time = end_time - start_time
print(f"Time taken for inference: {elapsed_time:.2f} seconds")

"""## Model 2: version 43-> YOLOv8n: Roboflow augmented dataset + yolo integrated augmentation"""

#Loading the previous(result 2) best iteration for training
model_path = "/content/drive/MyDrive/Colab Notebooks(NEHA)/Results/Result2/detect/train/weights/best.pt"
model = YOLO(model_path)

# Freeze wrt layer index
for i, (name, param) in enumerate(model.named_parameters()):
    if i < 22:
      param.requires_grad = False
      print(f"freezing Index {i}")



results = model.train(data="/content/drive/MyDrive/Colab Notebooks(NEHA)/Datasets/Augmented_dataset.v1i.yolov8/data.yaml",  epochs=100, optimizer= 'AdamW', batch=64,lr0=0.01, momentum=0.937, patience=50,hsv_h=0.015,hsv_s=0.7,degrees=0.0,scale=0.5,shear=0.5,perspective=0.0,flipud=0.2,fliplr=0.5,mosaic=1.0,translate=0.1)
metrics = model.val()

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard

tensorboard --logdir runs

"""## Running inference (Version 43) (test set)"""

import time

# Load the model
model_path = "/content/drive/MyDrive/Colab Notebooks(NEHA)/Results/Result43/detect/train/weights/best.pt"
model = YOLO(model_path)

# Define path to directory containing images and videos for inference
source = '/content/drive/MyDrive/Colab Notebooks(NEHA)/Datasets/Augmented_dataset.v1i.yolov8/test/images'

# Start time recording
start_time = time.time()

# Run inference on the source
results = model.predict(source, save=True, show=True, show_labels=True, show_boxes=True, show_conf=True)

# End time recording
end_time = time.time()

# Calculate and print the elapsed time
elapsed_time = end_time - start_time
print(f"Time taken for inference: {elapsed_time:.2f} seconds")

"""Running validation on it to get the scores"""

import time
# Load the model
model_path = "/content/drive/MyDrive/Colab Notebooks(NEHA)/Results/Result43/detect/train/weights/best.pt"
model = YOLO(model_path)

# Define path to directory containing images and videos for inference
#data = '/content/drive/MyDrive/Colab Notebooks(NEHA)/Datasets/Pothole data augmentation2.v4i.yolov8/test/images'

# Start time recording
start_time = time.time()

#changing the path in data.yaml for test set
metrics = model.val(data ="/content/drive/MyDrive/Colab Notebooks(NEHA)/Datasets/Pothole.v1-raw.yolov8/Pothole.v1-raw.yolov8/data_test.yaml", iou=0.6, save=True)

# End time recording
end_time = time.time()

# Calculate and print the elapsed time
elapsed_time = end_time - start_time
print(f"Time taken for inference: {elapsed_time:.2f} seconds")

"""## Model 3: version 31-> YOLOv10n: Yolo integrated augmentation"""

# Load YOLOv10 model from pre trained
model = YOLO("yolov10n.pt")
# Freeze
freeze = [f"model.{x}." for x in range(23)]  # layers to freeze even frezzing 22 gave the same result
for k, v in model.named_parameters():
    v.requires_grad = True  # train all layers
    if any(x in k for x in freeze):
        print(f"freezing {k}")
        v.requires_grad = False

# Train the model
model.train(data="/content/drive/MyDrive/Colab Notebooks(NEHA)/Datasets/Pothole.v1-raw.yolov8/Pothole.v1-raw.yolov8/data.yaml", epochs=300, optimizer= 'AdamW', batch=64,lr0=0.01, momentum=0.937, patience=50,hsv_h=0.015,hsv_s=0.7,degrees=0.0,scale=0.5,shear=0.5,perspective=0.0,flipud=0.2,fliplr=0.5,mosaic=1.0,translate=0.1)

metrics = model.val()

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard

tensorboard --logdir runs

"""## Running inference (Version 31) (test set)"""

import time

# Load the model
model_path = "/content/drive/MyDrive/Colab Notebooks(NEHA)/Results/Result31/detect/train/weights/best.pt"
model = YOLO(model_path)

# Define path to directory containing images and videos for inference
source = '/content/drive/MyDrive/Colab Notebooks(NEHA)/Datasets/Pothole.v1-raw.yolov8/Pothole.v1-raw.yolov8/test/images'

# Start time recording
start_time = time.time()

# Run inference on the source
results = model.predict(source, save=True, show=True, show_labels=True, show_boxes=True, show_conf=True)

# End time recording
end_time = time.time()

# Calculate and print the elapsed time
elapsed_time = end_time - start_time
print(f"Time taken for inference: {elapsed_time:.2f} seconds")

"""Running validation on it to get the scores"""

import time
# Load the model
model_path = "/content/drive/MyDrive/Colab Notebooks(NEHA)/Results/Result31/detect/train/weights/best.pt"
model = YOLO(model_path)

# Define path to directory containing images and videos for inference
#data = '/content/drive/MyDrive/Colab Notebooks(NEHA)/Datasets/Pothole data augmentation2.v4i.yolov8/test/images'

# Start time recording
start_time = time.time()

#changing the path in data.yaml for test set
metrics = model.val(data ="/content/drive/MyDrive/Colab Notebooks(NEHA)/Datasets/Pothole.v1-raw.yolov8/Pothole.v1-raw.yolov8/data_test.yaml", iou=0.6, save=True)

# End time recording
end_time = time.time()

# Calculate and print the elapsed time
elapsed_time = end_time - start_time
print(f"Time taken for inference: {elapsed_time:.2f} seconds")

"""# UK Subset

## Running inference on UK dataset

## model 1
"""

import time

# Load the model
model_path = "/content/drive/MyDrive/Colab Notebooks(NEHA)/Results/Result37/detect/train/weights/best.pt"
model = YOLO(model_path)

# Define path to directory containing images for inference
source = '/content/drive/MyDrive/Colab Notebooks(NEHA)/Datasets/UK__dataset.v1i.yolov8/valid/images'

# Start time recording
start_time = time.time()

# Run inference on the source
results = model.predict(source, save=True, show=True, show_labels=True, show_boxes=True, show_conf=True)

# End time recording
end_time = time.time()

# Calculate and print the elapsed time
elapsed_time = end_time - start_time
print(f"Time taken for inference: {elapsed_time:.2f} seconds")

import time
# Load the model
model_path = "/content/drive/MyDrive/Colab Notebooks(NEHA)/Results/Result37/detect/train/weights/best.pt"
model = YOLO(model_path)


# Start time recording
start_time = time.time()

#changing the path in data.yaml for test set
metrics = model.val(data ="/content/drive/MyDrive/Colab Notebooks(NEHA)/Datasets/UK__dataset.v1i.yolov8/data.yaml", iou=0.6, save=True)

# End time recording
end_time = time.time()

# Calculate and print the elapsed time
elapsed_time = end_time - start_time
print(f"Time taken for inference: {elapsed_time:.2f} seconds")

"""## model 2"""

import time

# Load the model
model_path = "/content/drive/MyDrive/Colab Notebooks(NEHA)/Results/Result43/detect/train/weights/best.pt"
model = YOLO(model_path)

# Define path to directory containing images for inference
source = '/content/drive/MyDrive/Colab Notebooks(NEHA)/Datasets/UK__dataset.v1i.yolov8/valid/images'

# Start time recording
start_time = time.time()

# Run inference on the source
results = model.predict(source, save=True, show=True, show_labels=True, show_boxes=True, show_conf=True)

# End time recording
end_time = time.time()

# Calculate and print the elapsed time
elapsed_time = end_time - start_time
print(f"Time taken for inference: {elapsed_time:.2f} seconds")

import time
# Load the model
model_path = "/content/drive/MyDrive/Colab Notebooks(NEHA)/Results/Result43/detect/train/weights/best.pt"
model = YOLO(model_path)


# Start time recording
start_time = time.time()

#changing the path in data.yaml for test set
metrics = model.val(data ="/content/drive/MyDrive/Colab Notebooks(NEHA)/Datasets/UK__dataset.v1i.yolov8/data.yaml", iou=0.6, save=True)

# End time recording
end_time = time.time()

# Calculate and print the elapsed time
elapsed_time = end_time - start_time
print(f"Time taken for inference: {elapsed_time:.2f} seconds")



"""## model 3"""

import time

# Load the model
model_path = "/content/drive/MyDrive/Colab Notebooks(NEHA)/Results/Result31/detect/train/weights/best.pt"
model = YOLO(model_path)

# Define path to directory containing images for inference
source = '/content/drive/MyDrive/Colab Notebooks(NEHA)/Datasets/UK__dataset.v1i.yolov8/valid/images'

# Start time recording
start_time = time.time()

# Run inference on the source
results = model.predict(source, save=True, show=True, show_labels=True, show_boxes=True, show_conf=True)

# End time recording
end_time = time.time()

# Calculate and print the elapsed time
elapsed_time = end_time - start_time
print(f"Time taken for inference: {elapsed_time:.2f} seconds")

import time
# Load the model
model_path = "/content/drive/MyDrive/Colab Notebooks(NEHA)/Results/Result31/detect/train/weights/best.pt"
model = YOLO(model_path)


# Start time recording
start_time = time.time()

#changing the path in data.yaml for test set
metrics = model.val(data ="/content/drive/MyDrive/Colab Notebooks(NEHA)/Datasets/UK__dataset.v1i.yolov8/data.yaml", iou=0.6, save=True)

# End time recording
end_time = time.time()

# Calculate and print the elapsed time
elapsed_time = end_time - start_time
print(f"Time taken for inference: {elapsed_time:.2f} seconds")